export const dragTypes = {
  CARD: 'CARD'
}

export const actions = {
  FETCH_CARDS: 'FETCH_CARDS',
  UPDATE_CARD_STATUS: 'UPDATE_CARD_STATUS',
  UPDATE_CARD_POSITION: 'UPDATE_CARD_POSITION',
  UPDATE_FILTER_VALUE: 'UPDATE_FILTER_VALUE',
  UPDATE_CURRENT_SEARCH: 'UPDATE_CURRENT_SEARCH',
  FETCH_SAVED_SEARCHES: 'FETCH_SAVED_SEARCHES',
  ADD_CARDS_TO_KANBAN: 'ADD_CARDS_TO_KANBAN',
  ADD_EVENT_TO_CARD: 'ADD_EVENT_TO_CARD',
  DELETE_EVENT_FROM_CARD: 'DELETE_EVENT_FROM_CARD'
}