export const dragTypes = {
  CARD: 'CARD'
}

export const actions = {
  FETCH_CARDS: 'FETCH_CARDS',
  UPDATE_CARD_STATUS: 'UPDATE_CARD_STATUS',
  UPDATE_CARD_POSITION: 'UPDATE_CARD_POSITION',
  UPDATE_FILTER_VALUE: 'UPDATE_FILTER_VALUE',
  UPDATE_CURRENT_SEARCH: 'UPDATE_CURRENT_SEARCH'
}